site_name: respo
theme:
  favicon: images/favicon.png
  icon:
    logo: material/list-status
  name: material
  palette:
    primary: light blue

repo_name: rafsaf/respo
repo_url: https://github.com/rafsaf/respo

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Overview: index.md
  - install.md
  - Usage:
      - usage/declaring_roles_and_permissions.md
      - usage/respo_create_cli.md
      - usage/get_respo_model.md
      - usage/user_have_permission.md
  - Reference:
      - reference/core.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - respo
