# Generated by Django 3.2.12 on 2022-03-09 00:13

from typing import List, Tuple

from django.db import migrations, models

import respo.fields.django


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="TheModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respo_field", respo.fields.django.DjangoRespoField()),
            ],
        ),
    ]
