name: Publish
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.8
        with:
          virtualenvs-create: false
      - name: Install requirements
        run: poetry install --no-dev
      - name: Build dists
        run: |
          rm -fR dist/ 
          poetry build
      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
